= ieugen.ro


== Unelte folosite

* http://cryogenweb.org/[CryogenWeb] ca generator static de site - pentru că Clojure
* https://fomantic-ui.com/[Foomantic UI] pentru stiluri (Semantic UI e mort)
* https://openjdk.java.net/[Java] platformă pentru Cryogen-Web ( Closure / Leiningen )


=== Cum să construiești websitul

Situl folosește cryogenweb.
Citește documentația de acolo cel puțin o dată.

[source,shell]
--
    # Afișează proiectele curente
    ./gradlew projects

    # Generează HTML și PDF
    ./gradlew asciidoctor asciidoctorPdf

    # Construiește situl și pornește un server web local
    lein run
    cd site-build && python3 -m http.server

    # Pornește situl în mod dezvoltare - randează paginile instant
    lein ring server
--


=== Conversie CV

Momentan CV-ul este scris în AsciiDoc.
Folosim unealta CLI asciidoctorjs pentru conversie:

https://docs.asciidoctor.org/asciidoctor.js/latest/cli/install/

[source,shell]
--
# instalăm asciidoctor
npm i -g asciidoctor

# Convertim versiunea en în HTML
cd cv/

# Export to HTML
asciidoctor -a includedir=. -a published-cv="https://ieugen.ro/cv/en" -a langName='English' -D . asciidoc/en/index.adoc

# Export to pdf
asciidoctor-pdf -a includedir=. -a published-cv="https://ieugen.ro/cv/en" -a langName='English' -D . asciidoc/en/index.adoc

--
