= ieugen.ro


== Unelte folosite

* http://cryogenweb.org/[CryogenWeb] ca generator static de site - pentru că Clojure
* https://fomantic-ui.com/[Foomantic UI] pentru stiluri (Semantic UI e mort)
* https://openjdk.java.net/[Java] platformă pentru Cryogen-Web ( Closure / Leiningen )


=== Cum să construiești websitul

Situl folosește cryogenweb.
Citește documentația de acolo cel puțin o dată.

[source,shell]
--
    npm install -g sass

    # Pornește situl în mod dezvoltare - randează paginile instant
    clojure -X:serve
--


=== Conversie CV

Momentan CV-ul este scris în AsciiDoc.
Folosim unealta CLI asciidoctorjs pentru conversie:

https://docs.asciidoctor.org/asciidoctor.js/latest/cli/install/

[source,shell]
--
# instalăm asciidoctor
npm i -g asciidoctor

# Convertim versiunea en în HTML
cd cv/

# Export to HTML
asciidoctor -a includedir=. -a published-cv="https://ieugen.ro/cv/en" -a langName='English' -D ../content/cv/en asciidoc/en/index.adoc

# Export to pdf
asciidoctor-pdf -a includedir=. -a published-cv="https://ieugen.ro/cv/en" -a langName='English' -D ../content/cv/en -o cv.pdf asciidoc/en/index.adoc

--
