{:title "Setting sites under maintenance"
 :draft? true
 :description "We have sites under maintenance functionality here and we provide it by making a file available under a specific path."}

== Sites under maintenance

We have sites under maintenance functionality here and we provide it by making a file available under a specific path.
See gatway.cfg for details.

To put https://blog.ieugen.ro/ under maintenance, you need to copy `/usr/share/nginx/html/maintenance.html` to `/data/html/maintenance.beta.html`.

.Put site under maintenance
[source,shell]
--
   docker ps
   docker exec -ti gateway_nginx.xxxx sh
   # Put searchbeta site under maintenance by creating file
   cp /usr/share/nginx/html/maintenance-page.html /data/html/maintenance.beta.html
   cp /usr/share/nginx/html/maintenance-page.html /data/html/maintenance.dev.html
   cp /usr/share/nginx/html/maintenance-page.html /data/html/maintenance.prod.html
   cp /usr/share/nginx/html/maintenance-page.html /data/html/maintenance.staging.html

   # Remve site from maintenance
   rm /data/html/maintenance.beta.html
--

* https://medium.com/@fro_g/healthchecks-for-nginx-in-docker-dbdc0f8b3772
* https://gist.github.com/pitch-gist/2999707
* https://www.joergfelser.at/redirecting-to-a-custom-nginx-maintenance-page/

Protip: Using this method makes it easy to schedule maintenance’s with cronjobs!
