#+TITLE: Eugen și Bianca se iau
#+AUTHOR: Eugen Stan
#+EMAIL: eugen@ieugen.ro
#+LANGUAGE: ro
#+OPTIONS: toc:2 html5-fancy:t

* Urmează să ne căsătorim
* Au mai rămas
* Povestea noastră
** Ne-am cunoscut
** Ne-am logodit
** Ne căsătorim
* Vă invităm la nuntă
** Alături de părinții
*** Silvia și Marian Toma
*** Nela și Ion Stan
** Și de nașii
*** Georgiana și Adrian Petre
*** Diana și Cătălin Nicoară
* Când?
*8 Iulie 2023*
* Unde?
Complex Turistic BellaVista Săcele
Strada 7 Izvoare 44, Săcele, Brașov 505600
* Program eveniment

Toate evenimentele se desfășoară în același loc, în poiana complexului sau în restaurant.

- Cununie civilă:: ~13:00
- Cununie religioasă:: ~13:30
- Gustare:: 15:00
- Dansul mirilor:: 16:00
- Pește:: 17:00
- Candy bar:: 17:00
- Tradițional (sarmale):: 19:00
- Friptură:: 21:00
- Tort:: 23:00
- Petrecere:: până pe la 01:00, sau cât se poate.

Cununia civilă și religioasă se desfășoară una după alta în poiana complexului.
După care oaspeții sunt invitați să intre în restaurant pentru servirea aperitivului și începerea evenimentului.

Gustare:
Salam banatean, Rosie umpluta cu salată de vinete, Ciuperca umpluta (dovlecel, ciuperci si cascaval), Julien din piept de pui, Rulou cu salată a la russe, Chiftelute,  Barcuta de ardei gras cu branza, Cascaval cu strugure, Castravete si masline
Peste:
Salau parizian, Orez sarbesc, Lamaie
Tradtional:
Sarmalute în foi de varza (cabanos / bacon), Mamaligă, Ardei iute si smantana
Friptura:
Gratar combinat din ceafa de porc și piept de pui, Cartofi cu rozmarin, Salata de varza alba

* Dress code

* Confirmare
Vă rugăm să confirmați prezența cât mai curând posibil, până pe *18 IUNIE 2023*.
Cel mai bine să completați formularul de mai jos
Telefon:
Bianca: [[tel:(+40)721-218-179][(+40)721-218-179]]
Eugen: [[tel:(+40)720-898-747][(+40)720-898-747]]
