{:title  "Proces de urmat pentru a lua un client/contract"
 :layout :post
 :date   "2020-07-05"
 :tags   ["proces" "clienți" "procedură"]
 :author "Eugen Exemplu"
 :description "Proces și pași de urmat atunci când considerăm un potențial client"
 :draft? true
 :lang "ro"}

== Netdava Quote for {netdava-prospect}

Eugen Stan <eugen.stan@netdava.com>
:netdava-prospect: Acme Incorporated

== Lista de cerințe este pentru {netdava-prospect}

* Afisarea unui banner care sa informeze vizitatorii despre aparitia unor evenimente sau
modificari ale programului de lucru.
* Inlocuirea listei de preturi aferenta link-ului "Preturile noastre le gasiti aici" cu lista
corespunzatoare fiecarui serviciu.
* Ca urmare a analizei cerințelor am venit cu următoarele oferte pentru Quickdesign.

== Obligații pentru client

Clientul trebuie să ofere toate materialele care trebuiesc afișate pe site.

Acestea includ:

* Design banner, design pentru tabele preturi
* Acces la site/CMS pentru a putea aplica modificarile
* Informatiile si textele necesare actualizarilor

== Oferta

* posibilitatea de a notifica clientii prin afisarea pe site a unui banner cu:
** logo-ul "quickdesign"
** text informativ privind modificari ale programului de lucru sau aparitia unor evenimente
** posibilitatea de a modifica cu usurinta textul prin editarea unui fisier
* posibilitatea de actualizare cu ușurință a ofertei de preț pe site

== Livrare și plată

* Livrarea se va efectua in termen de doua saptamani din data semnarii contractului.
* Pretul serviciilor prestate este de 150 RON.
